apiVersion: apps/v1
kind: Deployment
metadata:
  name: tlpagamento-deployment
  labels:
    app: tlpagamento-deployment
spec:
  selector:
    matchLabels:
      app: tlpagamento
  replicas: 1
  template:
    metadata:
      labels:
        app: tlpagamento
    spec:
      containers:
        - name: tlpagamento
          image: tiulanchesacr.azurecr.io/tlpagamento:latest  
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1.0"                  
          ports:
            - containerPort: 8083
              name: tlpagament-port
          env:
            - name: DATASOURCE_URL
              valueFrom :
                configMapKeyRef :
                  name : tlpagamento-config
                  key :  ds_url

            - name: CONEXAO_KAFKA
              valueFrom :
                configMapKeyRef :
                  name : tlpagamento-config
                  key : conexao_kafka

            - name: ACCESS_TOKEN_MP
              valueFrom :
                configMapKeyRef :
                  name : tlpagamento-config
                  key :  acess_token_mp                  
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: tlpagament-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: tlpagament-port
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tlpagamento-svc
spec:
  selector:
    app: tlpagamento
  ports:
    - port: 8083
      targetPort: 8083
  type: LoadBalancer
